name = "jb-port-cdn"
type = "javascript"
account_id = "3fb262f75fdc8f23225659e36155b9b4"
workers_dev = true
route = ""
zone_id = ""

# Entry point
main = "cloudflare-worker/index.js"

compatibility_date = "2024-12-01"
