name = "jb-port-cdn"
account_id = "3fb262f75fdc8f23225659e36155b9b4"

[site]
bucket = "./assets"  # Make sure this is the correct directory for your site files

[env.production]
workers_dev = false
route = "your-custom-domain-if-applicable"
