name: Deploy to Cloudflare Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare Workers
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.9aUxEEpBOrOKQCq4okWyv8TqvyuI_HWM7s1pz3bR }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.3fb262f75fdc8f23225659e36155b9b4 }}
