name: Deploy to Cloudflare Worker

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enables manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler@latest
      
      - name: Debug Environment Variables
        run: env | sort
      
      - name: Set Environment Variables
        run: echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV

      - name: Test Wrangler Authentication
        run: CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} wrangler whoami

      - name: API Token
        run: CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
      - name: Deploy to Cloudflare Workers
        run: wrangler deploy